export type UsageViewModel = {
  ok: boolean;
  statusLabel: string;
  primaryModelName: string;
  timeWindow: string;
  resetInLabel: string;
  resetTimestamp: number | null;
  totalCount: number | null;
  remainingCount: number | null;
  usedCount: number | null;
  usedPercent: number | null;
  remainingPercent: number | null;
  intervalStatus: number | null;
  weeklyTotalCount: number | null;
  weeklyUsedCount: number | null;
  weeklyRemainingCount: number | null;
  weeklyUsedPercent: number | null;
  weeklyRemainingPercent: number | null;
  weeklyStatus: number | null;
  weeklyResetTimestamp: number | null;
  weeklyResetInLabel: string;
  models: Array<{
    name: string;
    timeWindow?: string;
    totalCount?: number;
    remainingCount?: number;
    usedCount?: number;
    tag?: string;
  }>;
  raw: unknown;
};
